#!/bin/bash

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source ${dir}/builder/helpers
source ${dir}/credentials

files=($(find ${dir}/*.zip))
for item in ${files[*]}
do
	echo ${item}
	curl -X POST "https://${BB_LOGIN}@api.bitbucket.org/2.0/repositories/nerva-project/nerva.gui/downloads" --form files=@"${item}"
	curl -X POST "https://${BB_LOGIN}@api.bitbucket.org/2.0/repositories/nerva-project/nerva.gui/downloads" --form files=@"${item}.sig"
done
