#!/bin/bash

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source ${dir}/credentials

function deploy()
{
	target_file=$1
	sig_file=${target_file}.sig

	if [ -f ${dir}/${sig_file} ]; then
		echo "Signature file already exists"
	else
		gpg --detach-sign --default-key ${GPG_KEY_EMAIL} ${dir}/${target_file}
	fi

	echo Uploading ${target_file}
	curl --verbose "https://${BB_USERNAME}:${BB_PASS}@api.bitbucket.org/2.0/repositories/nerva-xnv/gui/downloads" --form files=@"${target_file}"
	curl --verbose "https://${BB_USERNAME}:${BB_PASS}@api.bitbucket.org/2.0/repositories/nerva-xnv/gui/downloads" --form files=@"${sig_file}"
}
