#!/bin/bash

BUILDER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source ${BUILDER_DIR}/helpers
detectversion

function preclean()
{
    find ${NERVA_DIR}/External -iname "bin" -o -iname "obj" | xargs rm -rf
    find ${NERVA_DIR}/Src -iname "bin" -o -iname "obj" | xargs rm -rf
}

function postclean()
{
    find ${NERVA_DIR}/Bin -iname "*.pdb" | xargs rm -rf
}

function build()
{
    rm -rf ${NERVA_DIR}/Bin/$1/$2

    preclean

    #dotnet restore ${NERVA_DIR}/Src/Nerva.Toolkit/Nerva.Toolkit.$2.csproj
    #dotnet build -c $1 ${NERVA_DIR}/Src/Nerva.Toolkit/Nerva.Toolkit.$2.csproj

    dotnet publish /t:restore /t:build \
    /p:GenerateFullPaths=true /p:Configuration=$1 /p:TrimUnusedDependencies=true \
    ${NERVA_DIR}/Src/Nerva.Toolkit/Nerva.Toolkit.$2.csproj

    postclean
}

function linux()
{
    build Release Linux
}

function mac()
{
    build Release Mac
}

function windows()
{
    build Release Windows
}

$1
