#!/bin/bash

#Launcher64 is taken from the Eto.Forms.Mac64 2.5.0-ci-10024 nuget package

BUILDER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source ${BUILDER_DIR}/helpers
detectversion

function mac()
{
	macdir=${NERVA_DIR}/Bin/Release/Mac

	mkdir -p ${macdir}/Contents
	mkdir -p ${macdir}/Contents/MacOS
	mkdir -p ${macdir}/Contents/MonoBundle
	mkdir -p ${macdir}/Contents/Resources

	find ${macdir}/ -maxdepth 1 -type f -name '*' -exec mv -n {} ${macdir}/Contents/MonoBundle \;

	plist=$(sed -e "s/{NERVA_VERSION}/${NERVA_VERSION}/" -e "s/{DISPLAY_NAME}/${NERVA_CODENAME}/" ${BUILDER_DIR}/Info.plist.template)
	echo "$plist" > ${macdir}/Contents/info.plist

	cp ${BUILDER_DIR}/logos/nerva-logo-color.icns ${macdir}/Contents/Resources/nerva-logo-color.icns
	cp ${BUILDER_DIR}/logos/nerva-logo-color-2.icns ${macdir}/Contents/Resources/nerva-logo-color-2.icns

	cp ${NERVA_DIR}/External/Eto/src/Eto.Mac/build/Launcher64 ${macdir}/Contents/MacOS/Nerva.Toolkit

	mv ${macdir} ${NERVA_DIR}/Bin/Release/Nerva.Toolkit.app

	cd ${NERVA_DIR}/Bin/Release
	mkdir -p ${NERVA_DIR}/Bin/Publish
	zip -r ${NERVA_DIR}/Bin/Publish/nerva-gui-v${NERVA_VERSION}_osx.zip Nerva.Toolkit.app/
}

function windows()
{
	cd ${NERVA_DIR}/Bin/Release/Windows
	mkdir -p ${NERVA_DIR}/Bin/Publish
	zip -r ${NERVA_DIR}/Bin/Publish/nerva-gui-v${NERVA_VERSION}_windows.zip ./*
}

function linux()
{
	cd ${NERVA_DIR}/Bin/Release/Linux
	mkdir -p ${NERVA_DIR}/Bin/Publish
	zip -r ${NERVA_DIR}/Bin/Publish/nerva-gui-v${NERVA_VERSION}_linux.zip ./*
}

$1
