#!/bin/bash

BUILDER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source ${BUILDER_DIR}/helpers
detectversion

function windows()
{
	cd ${NERVA_DIR}/Bin/Release/Windows
	mkdir -p ${NERVA_DIR}/Bin/Publish
	zip -r ${NERVA_DIR}/Bin/Publish/nerva-gui-v${NERVA_VERSION}_windows.zip ./*
}

$1
